// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/calendar.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Location      string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	CalendarId    string                 `protobuf:"bytes,6,opt,name=calendar_id,json=calendarId,proto3" json:"calendar_id,omitempty"` // defaults to "primary"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEventRequest) Reset() {
	*x = AddEventRequest{}
	mi := &file_proto_calendar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEventRequest) ProtoMessage() {}

func (x *AddEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEventRequest.ProtoReflect.Descriptor instead.
func (*AddEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_calendar_proto_rawDescGZIP(), []int{0}
}

func (x *AddEventRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddEventRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddEventRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *AddEventRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *AddEventRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *AddEventRequest) GetCalendarId() string {
	if x != nil {
		return x.CalendarId
	}
	return ""
}

type AddEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	HtmlLink      string                 `protobuf:"bytes,4,opt,name=html_link,json=htmlLink,proto3" json:"html_link,omitempty"`       // Link to view in Google Calendar
	CalendarId    string                 `protobuf:"bytes,5,opt,name=calendar_id,json=calendarId,proto3" json:"calendar_id,omitempty"` // Which calendar was used
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEventResponse) Reset() {
	*x = AddEventResponse{}
	mi := &file_proto_calendar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEventResponse) ProtoMessage() {}

func (x *AddEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEventResponse.ProtoReflect.Descriptor instead.
func (*AddEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_calendar_proto_rawDescGZIP(), []int{1}
}

func (x *AddEventResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AddEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddEventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AddEventResponse) GetHtmlLink() string {
	if x != nil {
		return x.HtmlLink
	}
	return ""
}

func (x *AddEventResponse) GetCalendarId() string {
	if x != nil {
		return x.CalendarId
	}
	return ""
}

var File_proto_calendar_proto protoreflect.FileDescriptor

const file_proto_calendar_proto_rawDesc = "" +
	"\n" +
	"\x14proto/calendar.proto\x12\bcalendar\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf8\x01\n" +
	"\x0fAddEventRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12\x1f\n" +
	"\vcalendar_id\x18\x06 \x01(\tR\n" +
	"calendarId\"\x9f\x01\n" +
	"\x10AddEventResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1b\n" +
	"\thtml_link\x18\x04 \x01(\tR\bhtmlLink\x12\x1f\n" +
	"\vcalendar_id\x18\x05 \x01(\tR\n" +
	"calendarId2T\n" +
	"\x0fCalendarService\x12A\n" +
	"\bAddEvent\x12\x19.calendar.AddEventRequest\x1a\x1a.calendar.AddEventResponseB}\n" +
	"\fcom.calendarB\rCalendarProtoP\x01Z\x1egithub.com/drewfead/cali/proto\xa2\x02\x03CXX\xaa\x02\bCalendar\xca\x02\bCalendar\xe2\x02\x14Calendar\\GPBMetadata\xea\x02\bCalendarb\x06proto3"

var (
	file_proto_calendar_proto_rawDescOnce sync.Once
	file_proto_calendar_proto_rawDescData []byte
)

func file_proto_calendar_proto_rawDescGZIP() []byte {
	file_proto_calendar_proto_rawDescOnce.Do(func() {
		file_proto_calendar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_calendar_proto_rawDesc), len(file_proto_calendar_proto_rawDesc)))
	})
	return file_proto_calendar_proto_rawDescData
}

var file_proto_calendar_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_calendar_proto_goTypes = []any{
	(*AddEventRequest)(nil),       // 0: calendar.AddEventRequest
	(*AddEventResponse)(nil),      // 1: calendar.AddEventResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_proto_calendar_proto_depIdxs = []int32{
	2, // 0: calendar.AddEventRequest.start_time:type_name -> google.protobuf.Timestamp
	2, // 1: calendar.AddEventRequest.end_time:type_name -> google.protobuf.Timestamp
	0, // 2: calendar.CalendarService.AddEvent:input_type -> calendar.AddEventRequest
	1, // 3: calendar.CalendarService.AddEvent:output_type -> calendar.AddEventResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_calendar_proto_init() }
func file_proto_calendar_proto_init() {
	if File_proto_calendar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_calendar_proto_rawDesc), len(file_proto_calendar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_calendar_proto_goTypes,
		DependencyIndexes: file_proto_calendar_proto_depIdxs,
		MessageInfos:      file_proto_calendar_proto_msgTypes,
	}.Build()
	File_proto_calendar_proto = out.File
	file_proto_calendar_proto_goTypes = nil
	file_proto_calendar_proto_depIdxs = nil
}
