// Code generated by protoc-gen-cli. DO NOT EDIT.

package proto

import (
	"context"
	"fmt"
	protocli "github.com/drewfead/proto-cli"
	v3 "github.com/urfave/cli/v3"
	grpc "google.golang.org/grpc"
	insecure "google.golang.org/grpc/credentials/insecure"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	"io"
	"os"
)

// getOutputWriter opens the specified output file or returns stdout
func getOutputWriter(path string) (io.Writer, error) {
	if path == "-" || path == "" {
		return os.Stdout, nil
	}
	return os.Create(path)
}

// CalendarServiceServiceCommand creates a service CLI for CalendarService with options
// The implOrFactory parameter can be either a direct service implementation or a factory function
func CalendarServiceServiceCommand(ctx context.Context, implOrFactory interface{}, opts ...protocli.ServiceOption) *protocli.ServiceCLI {
	options := protocli.ApplyServiceOptions(opts...)

	// Determine default format (first registered format, or empty if none)
	var defaultFormat string
	if len(options.OutputFormats()) > 0 {
		defaultFormat = options.OutputFormats()[0].Name()
	}

	var commands []*v3.Command

	// Build flags for add-event
	flags_add_event := []v3.Flag{&v3.StringFlag{
		Name:  "remote",
		Usage: "Remote gRPC server address (host:port). If set, uses gRPC client instead of direct call",
	}, &v3.StringFlag{
		Name:  "format",
		Usage: "Output format (use --format to see available formats)",
		Value: defaultFormat,
	}, &v3.StringFlag{
		Name:  "output",
		Usage: "Output file (- for stdout)",
		Value: "-",
	}}

	flags_add_event = append(flags_add_event, &v3.StringFlag{
		Name:  "title",
		Usage: "Title",
	})
	flags_add_event = append(flags_add_event, &v3.StringFlag{
		Name:  "description",
		Usage: "Description",
	})
	flags_add_event = append(flags_add_event, &v3.StringFlag{
		Name:  "start-time",
		Usage: "StartTime (google.protobuf.Timestamp)",
	})
	flags_add_event = append(flags_add_event, &v3.StringFlag{
		Name:  "end-time",
		Usage: "EndTime (google.protobuf.Timestamp)",
	})
	flags_add_event = append(flags_add_event, &v3.StringFlag{
		Name:  "location",
		Usage: "Location",
	})
	flags_add_event = append(flags_add_event, &v3.StringFlag{
		Name:  "calendar-id",
		Usage: "CalendarId",
	})

	// Add format-specific flags from registered formats
	for _, outputFmt := range options.OutputFormats() {
		// Check if format implements FlagConfiguredOutputFormat
		if flagConfigured, ok := outputFmt.(protocli.FlagConfiguredOutputFormat); ok {
			flags_add_event = append(flags_add_event, flagConfigured.Flags()...)
		}
	}

	commands = append(commands, &v3.Command{
		Action: func(cmdCtx context.Context, cmd *v3.Command) error {
			if options.BeforeCommand() != nil {
				if err := options.BeforeCommand()(cmdCtx, cmd); err != nil {
					return fmt.Errorf("before hook failed: %w", err)
				}
			}

			defer func() {
				if options.AfterCommand() != nil {
					if err := options.AfterCommand()(cmdCtx, cmd); err != nil {
						fmt.Fprintf(os.Stderr, "after hook failed: %v\n", err)
					}
				}
			}()

			// Build request message
			var req *AddEventRequest

			// Check for custom flag deserializer for calendar.AddEventRequest
			deserializer, hasDeserializer := options.FlagDeserializer("calendar.AddEventRequest")
			if hasDeserializer {
				// Use custom deserializer for top-level request
				// Create FlagContainer (deserializer can access multiple flags via Command())
				requestFlags := protocli.NewFlagContainer(cmd, "")
				msg, err := deserializer(cmdCtx, requestFlags)
				if err != nil {
					return fmt.Errorf("custom deserializer failed: %w", err)
				}
				// Handle nil return from deserializer
				if msg == nil {
					return fmt.Errorf("custom deserializer returned nil message")
				}
				var ok bool
				req, ok = msg.(*AddEventRequest)
				if !ok {
					return fmt.Errorf("custom deserializer returned wrong type: expected *%s, got %T", "AddEventRequest", msg)
				}
			} else {
				// Use auto-generated flag parsing
				req = &AddEventRequest{}
				req.Title = cmd.String("title")
				req.Description = cmd.String("description")
				// Field StartTime: check for custom deserializer for google.protobuf.Timestamp
				if fieldDeserializer, hasFieldDeserializer := options.FlagDeserializer("google.protobuf.Timestamp"); hasFieldDeserializer {
					// Use custom deserializer for nested message
					// Create FlagContainer for field flag: start-time
					fieldFlags := protocli.NewFlagContainer(cmd, "start-time")
					fieldMsg, fieldErr := fieldDeserializer(cmdCtx, fieldFlags)
					if fieldErr != nil {
						return fmt.Errorf("failed to deserialize field StartTime: %w", fieldErr)
					}
					// Handle nil return from deserializer (means skip/use default)
					if fieldMsg != nil {
						typedField, fieldOk := fieldMsg.(*timestamppb.Timestamp)
						if !fieldOk {
							return fmt.Errorf("custom deserializer for google.protobuf.Timestamp returned wrong type: expected *Timestamp, got %T", fieldMsg)
						}
						req.StartTime = typedField
					}
				} else {
					// No custom deserializer - check if user provided a value
					if cmd.IsSet("start-time") {
						return fmt.Errorf("flag --start-time requires a custom deserializer for google.protobuf.Timestamp (register with protocli.WithFlagDeserializer)")
					}
					// No value provided - leave field as nil
				}
				// Field EndTime: check for custom deserializer for google.protobuf.Timestamp
				if fieldDeserializer, hasFieldDeserializer := options.FlagDeserializer("google.protobuf.Timestamp"); hasFieldDeserializer {
					// Use custom deserializer for nested message
					// Create FlagContainer for field flag: end-time
					fieldFlags := protocli.NewFlagContainer(cmd, "end-time")
					fieldMsg, fieldErr := fieldDeserializer(cmdCtx, fieldFlags)
					if fieldErr != nil {
						return fmt.Errorf("failed to deserialize field EndTime: %w", fieldErr)
					}
					// Handle nil return from deserializer (means skip/use default)
					if fieldMsg != nil {
						typedField, fieldOk := fieldMsg.(*timestamppb.Timestamp)
						if !fieldOk {
							return fmt.Errorf("custom deserializer for google.protobuf.Timestamp returned wrong type: expected *Timestamp, got %T", fieldMsg)
						}
						req.EndTime = typedField
					}
				} else {
					// No custom deserializer - check if user provided a value
					if cmd.IsSet("end-time") {
						return fmt.Errorf("flag --end-time requires a custom deserializer for google.protobuf.Timestamp (register with protocli.WithFlagDeserializer)")
					}
					// No value provided - leave field as nil
				}
				req.Location = cmd.String("location")
				req.CalendarId = cmd.String("calendar-id")
			}

			// Check if using remote gRPC call or direct implementation call
			remoteAddr := cmd.String("remote")
			var resp *AddEventResponse
			var err error

			if remoteAddr != "" {
				// Remote gRPC call
				conn, connErr := grpc.NewClient(remoteAddr, grpc.WithTransportCredentials(insecure.NewCredentials()))
				if connErr != nil {
					return fmt.Errorf("failed to connect to remote %s: %w", remoteAddr, connErr)
				}
				defer conn.Close()

				client := NewCalendarServiceClient(conn)
				resp, err = client.AddEvent(cmdCtx, req)
				if err != nil {
					return fmt.Errorf("remote call failed: %w", err)
				}
			} else {
				// Direct implementation call (no config)
				svcImpl := implOrFactory.(CalendarServiceServer)
				resp, err = svcImpl.AddEvent(cmdCtx, req)
				if err != nil {
					return fmt.Errorf("method failed: %w", err)
				}
			}

			// Open output writer
			outputWriter, err := getOutputWriter(cmd.String("output"))
			if err != nil {
				return fmt.Errorf("failed to open output: %w", err)
			}
			if closer, ok := outputWriter.(io.Closer); ok {
				defer closer.Close()
			}

			// Find and use the appropriate output format
			formatName := cmd.String("format")

			// Try registered formats
			for _, outputFmt := range options.OutputFormats() {
				if outputFmt.Name() == formatName {
					if err := outputFmt.Format(cmdCtx, cmd, outputWriter, resp); err != nil {
						return fmt.Errorf("format failed: %w", err)
					}
					return nil
				}
			}

			// Format not found - build list of available formats
			var availableFormats []string
			for _, f := range options.OutputFormats() {
				availableFormats = append(availableFormats, f.Name())
			}
			if len(availableFormats) == 0 {
				return fmt.Errorf("no output formats registered (use WithOutputFormats to register formats)")
			}
			return fmt.Errorf("unknown format %q (available: %v)", formatName, availableFormats)
		},
		Flags: flags_add_event,
		Name:  "add-event",
		Usage: "Call AddEvent RPC",
	})

	return &protocli.ServiceCLI{
		Command: &v3.Command{
			Commands: commands,
			Name:     "calendar-service",
			Usage:    "CLI for CalendarService",
		},
		ConfigMessageType: "",
		FactoryOrImpl:     implOrFactory,
		RegisterFunc: func(s *grpc.Server, impl interface{}) {
			RegisterCalendarServiceServer(s, impl.(CalendarServiceServer))
		},
		ServiceName: "calendar-service",
	}
}
