// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/config.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CaliConfig is the typed configuration for the cali CLI
type CaliConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Auth configuration
	Auth *AuthConfig `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	// Default calendar ID to use when not specified
	DefaultCalendarId string `protobuf:"bytes,2,opt,name=default_calendar_id,json=defaultCalendarId,proto3" json:"default_calendar_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CaliConfig) Reset() {
	*x = CaliConfig{}
	mi := &file_proto_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaliConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaliConfig) ProtoMessage() {}

func (x *CaliConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaliConfig.ProtoReflect.Descriptor instead.
func (*CaliConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{0}
}

func (x *CaliConfig) GetAuth() *AuthConfig {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *CaliConfig) GetDefaultCalendarId() string {
	if x != nil {
		return x.DefaultCalendarId
	}
	return ""
}

// AuthConfig holds authentication settings
type AuthConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service account credentials (takes priority if present)
	ServiceAccount *ServiceAccountCredentials `protobuf:"bytes,1,opt,name=service_account,json=serviceAccount,proto3" json:"service_account,omitempty"`
	// OAuth client credentials (used if service_account not present)
	OauthClient *OAuthClientCredentials `protobuf:"bytes,2,opt,name=oauth_client,json=oauthClient,proto3" json:"oauth_client,omitempty"`
	// Path to OAuth token file for caching (optional, defaults to ~/.config/cali/token.json)
	OauthTokenPath string `protobuf:"bytes,3,opt,name=oauth_token_path,json=oauthTokenPath,proto3" json:"oauth_token_path,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuthConfig) Reset() {
	*x = AuthConfig{}
	mi := &file_proto_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthConfig) ProtoMessage() {}

func (x *AuthConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthConfig.ProtoReflect.Descriptor instead.
func (*AuthConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{1}
}

func (x *AuthConfig) GetServiceAccount() *ServiceAccountCredentials {
	if x != nil {
		return x.ServiceAccount
	}
	return nil
}

func (x *AuthConfig) GetOauthClient() *OAuthClientCredentials {
	if x != nil {
		return x.OauthClient
	}
	return nil
}

func (x *AuthConfig) GetOauthTokenPath() string {
	if x != nil {
		return x.OauthTokenPath
	}
	return ""
}

// ServiceAccountCredentials contains Google Cloud service account credentials
// This mirrors the structure of a service account JSON key file
type ServiceAccountCredentials struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Type                    string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // Always "service_account"
	ProjectId               string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	PrivateKeyId            string                 `protobuf:"bytes,3,opt,name=private_key_id,json=privateKeyId,proto3" json:"private_key_id,omitempty"`
	PrivateKey              string                 `protobuf:"bytes,4,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"` // PEM-encoded private key
	ClientEmail             string                 `protobuf:"bytes,5,opt,name=client_email,json=clientEmail,proto3" json:"client_email,omitempty"`
	ClientId                string                 `protobuf:"bytes,6,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	AuthUri                 string                 `protobuf:"bytes,7,opt,name=auth_uri,json=authUri,proto3" json:"auth_uri,omitempty"`
	TokenUri                string                 `protobuf:"bytes,8,opt,name=token_uri,json=tokenUri,proto3" json:"token_uri,omitempty"`
	AuthProviderX509CertUrl string                 `protobuf:"bytes,9,opt,name=auth_provider_x509_cert_url,json=authProviderX509CertUrl,proto3" json:"auth_provider_x509_cert_url,omitempty"`
	ClientX509CertUrl       string                 `protobuf:"bytes,10,opt,name=client_x509_cert_url,json=clientX509CertUrl,proto3" json:"client_x509_cert_url,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ServiceAccountCredentials) Reset() {
	*x = ServiceAccountCredentials{}
	mi := &file_proto_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceAccountCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAccountCredentials) ProtoMessage() {}

func (x *ServiceAccountCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAccountCredentials.ProtoReflect.Descriptor instead.
func (*ServiceAccountCredentials) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceAccountCredentials) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ServiceAccountCredentials) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ServiceAccountCredentials) GetPrivateKeyId() string {
	if x != nil {
		return x.PrivateKeyId
	}
	return ""
}

func (x *ServiceAccountCredentials) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *ServiceAccountCredentials) GetClientEmail() string {
	if x != nil {
		return x.ClientEmail
	}
	return ""
}

func (x *ServiceAccountCredentials) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ServiceAccountCredentials) GetAuthUri() string {
	if x != nil {
		return x.AuthUri
	}
	return ""
}

func (x *ServiceAccountCredentials) GetTokenUri() string {
	if x != nil {
		return x.TokenUri
	}
	return ""
}

func (x *ServiceAccountCredentials) GetAuthProviderX509CertUrl() string {
	if x != nil {
		return x.AuthProviderX509CertUrl
	}
	return ""
}

func (x *ServiceAccountCredentials) GetClientX509CertUrl() string {
	if x != nil {
		return x.ClientX509CertUrl
	}
	return ""
}

// OAuthClientCredentials contains OAuth 2.0 client credentials
// This mirrors the structure of OAuth Desktop app credentials
type OAuthClientCredentials struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ClientId                string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret            string                 `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	ProjectId               string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	AuthUri                 string                 `protobuf:"bytes,4,opt,name=auth_uri,json=authUri,proto3" json:"auth_uri,omitempty"`
	TokenUri                string                 `protobuf:"bytes,5,opt,name=token_uri,json=tokenUri,proto3" json:"token_uri,omitempty"`
	AuthProviderX509CertUrl string                 `protobuf:"bytes,6,opt,name=auth_provider_x509_cert_url,json=authProviderX509CertUrl,proto3" json:"auth_provider_x509_cert_url,omitempty"`
	RedirectUris            []string               `protobuf:"bytes,7,rep,name=redirect_uris,json=redirectUris,proto3" json:"redirect_uris,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *OAuthClientCredentials) Reset() {
	*x = OAuthClientCredentials{}
	mi := &file_proto_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuthClientCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthClientCredentials) ProtoMessage() {}

func (x *OAuthClientCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuthClientCredentials.ProtoReflect.Descriptor instead.
func (*OAuthClientCredentials) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{3}
}

func (x *OAuthClientCredentials) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *OAuthClientCredentials) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *OAuthClientCredentials) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *OAuthClientCredentials) GetAuthUri() string {
	if x != nil {
		return x.AuthUri
	}
	return ""
}

func (x *OAuthClientCredentials) GetTokenUri() string {
	if x != nil {
		return x.TokenUri
	}
	return ""
}

func (x *OAuthClientCredentials) GetAuthProviderX509CertUrl() string {
	if x != nil {
		return x.AuthProviderX509CertUrl
	}
	return ""
}

func (x *OAuthClientCredentials) GetRedirectUris() []string {
	if x != nil {
		return x.RedirectUris
	}
	return nil
}

var File_proto_config_proto protoreflect.FileDescriptor

const file_proto_config_proto_rawDesc = "" +
	"\n" +
	"\x12proto/config.proto\x12\bcalendar\"f\n" +
	"\n" +
	"CaliConfig\x12(\n" +
	"\x04auth\x18\x01 \x01(\v2\x14.calendar.AuthConfigR\x04auth\x12.\n" +
	"\x13default_calendar_id\x18\x02 \x01(\tR\x11defaultCalendarId\"\xc9\x01\n" +
	"\n" +
	"AuthConfig\x12L\n" +
	"\x0fservice_account\x18\x01 \x01(\v2#.calendar.ServiceAccountCredentialsR\x0eserviceAccount\x12C\n" +
	"\foauth_client\x18\x02 \x01(\v2 .calendar.OAuthClientCredentialsR\voauthClient\x12(\n" +
	"\x10oauth_token_path\x18\x03 \x01(\tR\x0eoauthTokenPath\"\xfc\x02\n" +
	"\x19ServiceAccountCredentials\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12$\n" +
	"\x0eprivate_key_id\x18\x03 \x01(\tR\fprivateKeyId\x12\x1f\n" +
	"\vprivate_key\x18\x04 \x01(\tR\n" +
	"privateKey\x12!\n" +
	"\fclient_email\x18\x05 \x01(\tR\vclientEmail\x12\x1b\n" +
	"\tclient_id\x18\x06 \x01(\tR\bclientId\x12\x19\n" +
	"\bauth_uri\x18\a \x01(\tR\aauthUri\x12\x1b\n" +
	"\ttoken_uri\x18\b \x01(\tR\btokenUri\x12<\n" +
	"\x1bauth_provider_x509_cert_url\x18\t \x01(\tR\x17authProviderX509CertUrl\x12/\n" +
	"\x14client_x509_cert_url\x18\n" +
	" \x01(\tR\x11clientX509CertUrl\"\x94\x02\n" +
	"\x16OAuthClientCredentials\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x02 \x01(\tR\fclientSecret\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tR\tprojectId\x12\x19\n" +
	"\bauth_uri\x18\x04 \x01(\tR\aauthUri\x12\x1b\n" +
	"\ttoken_uri\x18\x05 \x01(\tR\btokenUri\x12<\n" +
	"\x1bauth_provider_x509_cert_url\x18\x06 \x01(\tR\x17authProviderX509CertUrl\x12#\n" +
	"\rredirect_uris\x18\a \x03(\tR\fredirectUrisB{\n" +
	"\fcom.calendarB\vConfigProtoP\x01Z\x1egithub.com/drewfead/cali/proto\xa2\x02\x03CXX\xaa\x02\bCalendar\xca\x02\bCalendar\xe2\x02\x14Calendar\\GPBMetadata\xea\x02\bCalendarb\x06proto3"

var (
	file_proto_config_proto_rawDescOnce sync.Once
	file_proto_config_proto_rawDescData []byte
)

func file_proto_config_proto_rawDescGZIP() []byte {
	file_proto_config_proto_rawDescOnce.Do(func() {
		file_proto_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_config_proto_rawDesc), len(file_proto_config_proto_rawDesc)))
	})
	return file_proto_config_proto_rawDescData
}

var file_proto_config_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_config_proto_goTypes = []any{
	(*CaliConfig)(nil),                // 0: calendar.CaliConfig
	(*AuthConfig)(nil),                // 1: calendar.AuthConfig
	(*ServiceAccountCredentials)(nil), // 2: calendar.ServiceAccountCredentials
	(*OAuthClientCredentials)(nil),    // 3: calendar.OAuthClientCredentials
}
var file_proto_config_proto_depIdxs = []int32{
	1, // 0: calendar.CaliConfig.auth:type_name -> calendar.AuthConfig
	2, // 1: calendar.AuthConfig.service_account:type_name -> calendar.ServiceAccountCredentials
	3, // 2: calendar.AuthConfig.oauth_client:type_name -> calendar.OAuthClientCredentials
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_config_proto_init() }
func file_proto_config_proto_init() {
	if File_proto_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_config_proto_rawDesc), len(file_proto_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_config_proto_goTypes,
		DependencyIndexes: file_proto_config_proto_depIdxs,
		MessageInfos:      file_proto_config_proto_msgTypes,
	}.Build()
	File_proto_config_proto = out.File
	file_proto_config_proto_goTypes = nil
	file_proto_config_proto_depIdxs = nil
}
